config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'results#index'
  resources :store_props do 
    collection { post :import }
    collection { get :export }
  end 

  resources :summit_clients, only: [:index, :show] do
    collection { post :import }
    collection { delete :all_delete }
  end

  resources :summits, expect: [:new, :create] do 
    collection { post :import }
    collection { post :import_price }
    collection { get :sw_error }
    collection { get :cancel }
    collection { delete :not_share_delete }
  end

  resources :summit_customer_props do 
    collection { post :import}
  end 

  resources :summit_error_histories do 
    collection { post :import }
  end 

  resources :summit_billing_amounts do 
    collection { post :import }
  end 

  resources :summit_date_progresses, only: [:index] do 
    collection {get :base}
  end 

  resources :summit_date_progresses, only: :show,param: :user_id


  resources :pranesses, expect: [:new, :create] do 
    collection { 
      post :import 
      get :simplified_chart
      get :not_payment
    }
  end 

  resources :payment_pranesses do 
    collection { 
      post :import 
      get :year_profit
      get :year_valuation
      get :not_payment
    }
  end 

  get "year_profit_price", to: "payment_pranesses#year_profit_price", as: "year_profit_price"
  get "year_profit_len", to: "payment_pranesses#year_profit_len", as: "year_profit_len"
  get "year_val_price", to: "payment_pranesses#year_val_price", as: "year_val_price"
  get "year_val_len", to: "payment_pranesses#year_val_len", as: "year_val_len"

  resources :praness_options do 
    collection {
      post :import 
    }
  end 

  resources :dmers do 
    collection { post :import }
    collection { get :index_export }
    collection { get :export }
    collection { get :simple_conf }
    collection { get :simple_conf_year }
    collection { get :deficiency }
  end 
  
  resources :stocks do 
    collection { post :import }
    resources :stock_histories
    resources :return_histories
  end 

  resources :aupays, expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :paypays, expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :airpays do
    collection { 
      post :import 
      get :simple_conf 
    }
  end
  
  resources :stock_histories, only: [:destroy]
  resources :return_histories, only: [:destroy]
  
  resources :pandas, expect: [:new, :create] do 
    collection {post :import}
  end 

  resources :users do 
    collection {post :comment_new}
    collection {put :comment_update}
  end

  resources :shifts,expect: [:show] do 
    collection do
      post :update_month
      delete :delete_month
      get :cashless
    end
  end 

  resources :shifts, only: :show,param: :user_id

  resources :panda_profits, only: :index

  resources :results,expect: [:show]  do 
    get 'result_cashes/new'
    post 'result_cashes/create'
    get 'result_types/new'
    post 'result_types/create'
    get 'result_casas/new'
    get 'result_summits/new'
    post 'result_summits/create'
    get 'type_reference_values/new'
    post 'type_reference_values/create'
    collection { 
      post :import 
      get :export
      get :date_progress
      get :monthly_progress
      get :ranking
      get :gross_profit
      get :profit
      get :base_profit
      get :daily_report
      get :dup_index
      post :comment_new
      put :comment_update
      get :out_come
      get :base_productivity
      get :team_productivity
      get :person_productivity
      get :product_status
      get :slmt_list
      get :deficiency
      get :inc_or_dec
      get :valuation_list
    }
  end
  resources :type_reference_values, only: [:edit, :update]

  resources :result_types do 
    resources :deal_attributes do
      collection do
        get :edit_all
        patch :update_all
      end
    end
end

  resources :results, only: :show, param: :result_id
  get "date_fin/:id", to: "results#date_fin", as: "date_fin"
  get "weekly_fin/:id", to: "results#weekly_fin", as: "weekly_fin"
  get "out_val/:id", to: "results#out_val", as: "out_val"
  get "out_val_all/:id", to: "results#out_val_all", as: "out_val_all"
  get "out_val_type/:id", to: "results#out_val_type", as: "out_val_type"
  get "store_val/:id", to: "results#store_val", as: "store_val"
  get "store_val_all/:id", to: "results#store_val_all", as: "store_val_all"
  get "visit_type_val/:id", to: "results#visit_type_val", as: "visit_type_val"

  get "monthly_get", to: "results#monthly_get", as: "monthly_get"
  get "monthly_get_base", to: "results#monthly_get_base", as: "monthly_get_base"
  get "sales_and_def", to: "results#sales_and_def", as: "sales_and_def"
  get "user_list", to: "results#user_list", as: "user_list"
  
  
  resources :results_base_valuations, only: :index
  get "valuation", to: "results_base_valuations#valuation", as: "valuation"
  get "standard_val", to: "results_base_valuations#standard_val", as: "standard_val"
  get "productivity", to: "results_base_valuations#productivity", as: "productivity"
  get "current_result", to: "results_base_valuations#current_result", as: "current_result"


  resources :ojts, only: :index do 
    collection { get :export }
    collection { get :index_export }
    collection { get :summary_export }
  end 
  resources :ojts, only: :show, param: :result_id

  resources :result_cashes do 
    collection { post :import}
  end
  resources :result_casas, expect: [:new, :create]
  resources :result_summits, expect: :show do 
    collection { get :base_profit }
    collection { get :person_data }
    collection { get :repeal_data }
    collection { get :sw_error_data }
    collection { get :error_history_data }
    collection { get :customer_prop_data }
    collection { get :billing_data }
    collection { get :prediction_data }
  end 
  resources :result_summits, only: :show,param: :user_id
  
  resources :n_results do 
    collection { post :import }
  end  

  resources :products
  
  resources :display_periods
  
  resources :trouble_ns do 
    collection { post :import }
  end

  resources :rakuten_casas ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :trouble_sses ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :st_insurances ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :rakuten_pays do 
    collection { 
      post :import
      get :index_export 
      get :deficiency
      get :deficiency_new
      get :simple_conf
      get :simple_conf_year
    }
  end 

  resources :error_pages
  
  resources :costs 

  resources :product_checkers, only: [:index]
  resources :product_tests, only: [:index]
  
  resources :result_sales, only: [:index] do 
    collection { post :import }
  end 

  resources :comments

  resources :def_respondings, only: [:index]
  
  resources :settlements, only: [:index]
  resources :other_products
  resources :dmer_stocks
  resources :product_targets
  resources :demaekans, only: [:index] do 
    collection {post :import}
  end 

  resources :profits, only: [:index] do 
    collection {get :sum_export}
    collection {get :index_export}
    collection {get :profit_export_by_spreadsheet}
    collection {get :product_export_by_spreadsheet}
  end
  # get 'profits', to: 'profits#index' do 
  #   collection {get :sum_export}
  # end 

  resources :calc_periods do 
    collection {
      get :cash_csv_export
      get :cash_valuation_csv_export
      get :weekly_data
    }
  end 

  get "val_users", to: "calc_periods#val_users", as: "val_users"

  
  resources :dmer_date_progresses do 
    collection {get :progress_create}
    collection {get :csv_export}
    collection {get :date_destroy}
  end 
  
  resources :aupay_date_progresses do 
    collection {get :progress_create}
    collection {get :csv_export}
    collection {get :date_destroy}
  end 

  resources :paypay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :rakuten_pay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end

  resources :airpay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :demaekan_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :austicker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :dmersticker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :airpaysticker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :cash_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :itsses do 
    collection {post :import}
  end 

  resources :itss_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :usen_pay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  
  resources :other_product_date_progresses, only: [:index] do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :airpay_stickers do 
    collection {post :import}
    collection {get :date_destroy}
  end 


  resources :payment_cashes 
  resources :payment_dmers do 
    collection { 
      post :import
      get :not_payment
      get :conf_index
      get :result1
      get :result2
      get :result3
    }
  end 

  resources :payment_dmer_senbais do 
    collection { 
      post :import
      get :not_payment
      get :conf_index
      get :result
    }
  end 

  resources :payment_rakuten_pays do 
    collection { 
      post :import
      get :not_payment
      get :conf_index

app/models/result_summit.rb
class ResultSummit < ApplicationRecord
  belongs_to :result
  with_options presence: true do 
    validates :result_id
  end
end

app/helpers/result_summits_helper.rb
module ResultSummitsHelper
end

app/views/result_summits/base_profit.html.erb
<script>
  window.chubu_ary=<%= @chubu_ary.to_json.html_safe %>;
  window.kansai_ary=<%= @kansai_ary.to_json.html_safe %>;
  window.kanto_ary=<%= @kanto_ary.to_json.html_safe %>;
  window.partner_ary=<%= @partner_ary.to_json.html_safe %>;
  window.other_ary=<%= @other_ary.to_json.html_safe %>;
</script>
<% days = ["日", "月", "火", "水", "木", "金", "土"] %>
<div data-scope-path="shared/header">
  <h1>サミット利益表</h1>
  <%= render "shared/header" %>
</div>
  <div class="main">
    <div data-scope-path="results/index">
        <h2>
          <%= link_to "<<", base_profit_result_summits_path(month:@month.prev_month), class:"link","data-turbolinks": false %>
          <%= @month.month %>月
          <%= link_to ">>", base_profit_result_summits_path(month:@month.next_month), class:"link","data-turbolinks": false %>
        </h2>
    </div>
  </div>
  <%= javascript_pack_tag 'summit_profit' %>
  <%= stylesheet_pack_tag 'summit_profit' %>

app/views/result_summits/billing_data.html.erb
<%# サミット個別獲得案件一覧 %>
<% days = ["日", "月", "火", "水", "木", "金", "土"] %>
<div data-scope-path="shared/header">
  <h1>明細一覧</h1>
  <%= render "shared/header" %>
</div>
<div data-scope-path="users/show"><%# users/showスコープ頭 %>
    <h2>
      <%= @user.name %>
      <%= link_to "<<",billing_data_result_summits_path(user_id: @user.id,month:@month.prev_month),"data-turbolinks": false, class:"link" %>
      <%= @billing_month %> 明細一覧
      <%= link_to ">>",billing_data_result_summits_path(user_id: @user.id,month:@month.next_month),"data-turbolinks": false, class:"link" %>
    </h2><br>
    <%= render "shared/summit_result_links" %>

  <p class="caution-text">※平均手数料, 平均使用量に関しては初回発行された明細は除いて計算おります。</p>
  <table>
    <tr>
      <th class="date-th" colspan="4">明細件数</th>
      <th class="date-th" colspan="2">平均使用量</th>
      <th class="date-th" colspan="2">平均手数料</th>
      <th class="date-th" colspan="2">合計手数料（初回 + 過去）</th>
      <th class="date-th" colspan="2">合計手数料（初回発行のみ）</th>
    </tr>
    <tr>
      <th class="date-th">初回</th>
      <th class="date-th">合計</th>
      <% 3.times do %>
      <th class="date-th">従量</th>
      <th class="date-th">低圧</th>
      <% end %>
      <% 2.times do %>
      <th class="date-th">使用量</th>
      <th class="date-th">手数料</th>
      <% end %>
    </tr>
    <tr>
      <td class="date-td"><%= @summits.where(first_flag: "初回").length %></td>
      <td class="date-td"><%= @summits.length %></td>
      <td class="date-td"><%= @summits.where("contract_type LIKE ?", "%従量%").length %></td>
      <td class="date-td"><%= @summits.where("contract_type LIKE ?", "%低圧%").length %></td>
      <td class="date-td"><%= @summits.where(first_flag: "過去発行済").where("contract_type LIKE ?", "%従量%").average(:total_use).round() rescue 0 %>kWh</td>
      <td class="date-td"><%= @summits.where(first_flag: "過去発行済").where("contract_type LIKE ?", "%低圧%").average(:total_use).round() rescue 0 %>kWh</td>
      <td class="date-td">¥<%= @summits.where(first_flag: "過去発行済").where("contract_type LIKE ?", "%従量%").average(:commission).round() rescue 0 %></td>
      <td class="date-td">¥<%= @summits.where(first_flag: "過去発行済").where("contract_type LIKE ?", "%低圧%").average(:commission).round() rescue 0 %></td>
      <td class="date-td"><%= @summits.sum(:total_use).to_s(:delimited) rescue 0 %>kWh</td>
      <td class="date-td">¥<%= @summits.sum(:commission).to_s(:delimited) rescue 0 %></td>
      <td class="date-td"><%= @summits.where(first_flag: "初回").sum(:total_use).to_s(:delimited) rescue 0 %>kWh</td>
      <td class="date-td">
        ¥<%= @summits.where(first_flag: "初回").sum(:commission).to_s(:delimited) rescue 0 %>
        （合計の<%= number_to_percentage(@summits.where(first_flag: "初回").sum(:commission).to_f / @summits.sum(:commission) * 100,precision: 0) %>）
      </td>
    </tr>
  </table>

  <% if @summits.present? %>
  <h2>◆明細一覧(<%= @summits.length %>件)
    <button class="display-btn">
      <%= link_to "全地域明細", billing_data_result_summits_path(user_id: @user.id,month:@month),"data-turbolinks": false, class: "reset-link" %>
    </button>
    <% @bases.each do |summit| %>
    <button class="display-btn">
      <%= link_to "#{summit.base}明細", billing_data_result_summits_path(user_id: @user.id,month:@month,base: summit.base),"data-turbolinks": false, class: "reset-link" %>
    </button>
    <% end %>
  </h2>
  <div class="index-form">
  <table>
    <tr>
      <th class="date-th">No</th>
      <th class="date-th">拠点</th>
      <th class="date-th">店舗名</th>
      <th class="date-th">請求月</th>
      <th class="date-th">契約種別</th>
      <th class="date-th">使用量(kWh)</th>
      <th class="date-th">請求額</th>
      <th class="date-th">手数料</th>
      <th class="date-th">報酬率</th>
      <th class="date-th">詳細</th>
    </tr>
    <% @summits.each_with_index do |s, i| %>
    <tr>
      <td class="date-td"><%= i + 1 %></td>
      <td class="date-td"><%= s.base %></td>
      <td class="date-td"><%= s.store_name %></td>
      <td class="date-td"><%= s.billing_date %></td>
      <td class="date-td"><%= s.contract_type %></td>
      <td class="date-td"><%= s.total_use %></td>
      <td class="date-td"><%= s.billing_amount.to_s(:delimited) rescue 0 %></td>
      <td class="date-td"><%= s.commission.to_s(:delimited) rescue 0 %></td>
      <td class="date-td"><%= s.rate %></td>
      <td class="date-td"><%= link_to "詳細", summit_billing_amount_path(s.id), "data-turbolinks": false, class: "link" %></td>
    </tr>
    <% end %>
  </table>
  </div>
  <% else %>
  <p class="caution-text">※まだ<%= @month.month %>月はまだ明細が発行されておりません。</p>
  <% end %>

    <p class="nav-text">
      グラフ：
      <select class="graph-slct" id="summit-graph-change" >
        <option value="手数料">手数料（合計）</option>
        <option value="従量電灯（件数）">獲得数（合計）</option>
        <option value="従量電灯手数料（平均）">手数料（平均）</option>
        <option value="従量電灯使用量（平均）">使用量（平均）</option>
      </select>
    </p>
    <div class="graph-form" id="metered-graph">
      <h2>◆<%= @month.year %>年：獲得推移</h2><br>
      <%= column_chart @count_chart %>
      <table>
        <tr>
          <th class="date-th">項目</th>
          <% @counter_m.each do |col| %>
          <th class="date-th"><%= col[0] %></th>
          <% end %>
        </tr>
        <tr>
          <th class="date-th">従量電灯</th>
          <% @counter_m.each do |count| %>
          <td class="date-td"><%= count[1].round().to_s(:delimited) %></td>
          <% end %>
        </tr>
        <tr>
          <th class="date-th">低圧電力</th>
          <% (@counter_m.length - @counter_m.length).times do %>
          <td class="date-td">0</td>
          <% end %>
          <% @counter_l.each do |count| %>
          <td class="date-td"><%= count[1].round().to_s(:delimited) %></td>
          <% end %>
        </tr>
      </table>
    </div>
  <div class="graph-form-first" id="commission-graph">
    <h2>◆<%= @month.year %>年：手数料（合計）</h2><br>
    <%= column_chart   @commission_chart,options = {
      thousands: ",",
      suffix: "円",
      xtitle: "請求月",
    } 
    %>
      <table>
        <tr>
          <th class="date-th">項目</th>
          <% @commission_sum_m.each do |col| %>
          <th class="date-th"><%= col[0] %></th>
          <% end %>
        </tr>
        <tr>
          <th class="date-th">従量電灯</th>
          <% @commission_sum_m.each do |commission| %>
          <td class="date-td">¥<%= commission[1].round().to_s(:delimited) %></td>
          <% end %>
        </tr>
        <tr>
          <th class="date-th">低圧電力</th>
          <% (@commission_sum_m.length - @commission_sum_l.length).times do %>
          <td class="date-td">0</td>
          <% end %>
          <% @commission_sum_l.each do |commission| %>
          <td class="date-td">¥<%= commission[1].round().to_s(:delimited) %></td>
          <% end %>
        </tr>
        <tr>
          <th class="date-th">合計</th>
          <% (@commission_sum_all.length - @commission_sum_all.length).times do %>
          <td class="date-td">0</td>
          <% end %>
          <% @commission_sum_all.each do |commission| %>
          <td class="date-td">¥<%= commission[1].round().to_s(:delimited) %></td>
          <% end %>
        </tr>
      </table>
  </div>
  <div class="graph-form" id="commission-ave-graph">
    <h2>◆<%= @month.year %>年：手数料（平均）</h2><br>
    <%= column_chart   @commission_ave_chart,options = {
      thousands: ",",
      suffix: "円",
      xtitle: "請求月",
    } 
    %>
  <table>
    <tr>
      <th class="date-th">項目</th>
      <% @commission_m_ave.each do |col| %>
      <th class="date-th"><%= col[0] %></th>
      <% end %>
    </tr>
    <tr>
      <th class="date-th">従量電灯</th>
      <% @commission_m_ave.each do |commission_ave| %>
      <td class="date-td">¥<%= commission_ave[1].round().to_s(:delimited) %></td>
      <% end %>
    </tr>
    <tr>
      <th class="date-th">低圧電力</th>
      <% (@commission_m_ave.length - @commission_l_ave.length).times do %>
      <td class="date-td">¥0</td>
      <% end %>
      <% @commission_l_ave.each do |commission_ave| %>
      <td class="date-td">¥<%= commission_ave[1].round().to_s(:delimited) %></td>
      <% end %>
    </tr>
  </table>
  </div>
  <div class="graph-form" id="total-use-ave-graph">
    <h2>◆<%= @month.year %>年：使用料（平均）</h2><br>
    <%= column_chart   @total_use_ave_chart,options = {
      thousands: ",",
      suffix: "kWh",
      xtitle: "請求月",
    } 
    %>
  
  <table>
    <tr>
      <th class="date-th">項目</th>
      <% @total_use_m_ave.each do |col| %>
      <th class="date-th"><%= col[0] %></th>
      <% end %>
    </tr>
    <tr>
      <th class="date-th">従量電灯</th>
      <% @total_use_m_ave.each do |total_use_ave| %>
      <td class="date-td"><%= total_use_ave[1].round(1) %>kWh</td>
      <% end %>
    </tr>
    <tr>
      <th class="date-th">低圧電力</th>
      <% (@total_use_m_ave.length - @total_use_m_ave.length).times do %>
      <td class="date-td">0kWh</td>
      <% end %>
      <% @total_use_l_ave.each do |total_use_ave| %>
      <td class="date-td"><%= total_use_ave[1].round(1) %>kWh</td>
      <% end %>
    </tr>
  </table>
  </div>
  <p class="caution-text">※平均手数料, 平均使用量に関しては初回発行された明細は除いて計算おります。</p>
</div>

app/views/result_summits/customer_prop_data.html.erb
<%# サミット個別獲得案件一覧 %>
<% days = ["日", "月", "火", "水", "木", "金", "土"] %>
<div data-scope-path="shared/header">
  <h1>個別対応履歴</h1>
  <%= render "shared/header" %>
</div>
<div data-scope-path="users/show"><%# users/showスコープ頭 %>
    <h2>
      <%= @user.name %>
      <%= link_to "<<",customer_prop_data_result_summits_path(user_id: @user.id,month:@month.prev_month), class:"link" %>
      <%= @month.year %>年<%= @month.month %>月 対応履歴
      <%= link_to ">>",customer_prop_data_result_summits_path(user_id: @user.id,month:@month.next_month), class:"link" %>
    </h2><br>
    <%= render "shared/summit_result_links" %>

  <table>
    <tr>
      <th class="date-th">No</th>
      <th class="date-th">店舗名</th>
      <th class="date-th">作成日時</th>
      <th class="date-th">タイトル</th>
      <th class="date-th">ステータス</th>
      <th class="date-th">対応依頼内容</th>
      <th class="date-th">次回対応依頼</th>
      <th class="date-th">詳細</th>
    </tr>
    <% @summits.each_with_index do |s, i| %>
    <tr>
      <td class="date-td"><%= i + 1 %></td>
      <td class="date-td"><%= s.store_name %></td>
      <td class="date-td"><%= s.create_datetime.to_date %></td>
      <td class="date-td"><%= s.title %></td>
      <td class="date-td"><%= s.status %></td>
      <td class="remarks-td"><%= s.next_request %></td>
      <td class="remarks-td"><%= s.response_remarks %></td>
      <td class="date-td"><%= link_to "詳細", summit_customer_prop_path(s.id), "data-turbolinks": false, class: "link" %></td>
    </tr>
    <% end %>
  </table>

</div>

app/views/result_summits/error_history_data.html.erb
<%# サミット個別獲得案件一覧 %>
<% days = ["日", "月", "火", "水", "木", "金", "土"] %>
<div data-scope-path="shared/header">
  <h1>SWエラー</h1>
  <%= render "shared/header" %>
</div>
<div data-scope-path="users/show"><%# users/showスコープ頭 %>
    <h2><%= @user.name %>：支払遅延案件一覧</h2><br>
    <%= render "shared/summit_result_links" %>

  <table>
    <tr>
      <th class="date-th">No</th>
      <th class="date-th">店舗名</th>
      <th class="date-th">未入金対象月</th>
      <th class="date-th">エラー区分2</th>
      <th class="date-th">対応内容・次回依頼</th>
      <th class="date-th">次回対応メモ</th>
      <th class="date-th">詳細</th>
    </tr>
    <% @summits.each_with_index do |s, i| %>
    <tr>
      <td class="date-td"><%= i + 1 %></td>
      <td class="date-td"><%= s.store_name %></td>
      <td class="date-td"><%= s.not_payment_month %></td>
      <td class="date-td"><%= s.error_class2 %></td>
      <td class="date-td remarks-td"><%= s.next_request %></td>
      <td class="date-td remarks-td"><%= s.response_remarks %></td>
      <td class="date-td"><%= link_to "詳細", summit_error_history_path(s.id), "data-turbolinks": false, class: "link" %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/result_summits/repeal_data.html.erb
<%# サミット個別獲得案件一覧 %>
<% days = ["日", "月", "火", "水", "木", "金", "土"] %>
<div data-scope-path="shared/header">
  <h1>個別廃止案件</h1>
  <%= render "shared/header" %>
</div>
<div data-scope-path="users/show"><%# users/showスコープ頭 %>
    <h2>
      <%= @user.name %>
      <%= link_to "<<",repeal_data_result_summits_path(user_id: @user.id,month:@month.prev_month), class:"link" %>
      <%= @month.year %>年<%= @month.month %>月 獲得詳細
      <%= link_to ">>",repeal_data_result_summits_path(user_id: @user.id,month:@month.next_month), class:"link" %>
    </h2><br>
    <%= render "shared/summit_result_links" %>

  <h2><%= @month.month %>月：廃止案件</h2>
  <table>
    <tr>
      <th class="date-th">No</th>
      <th class="date-th">kintone連携</th>
      <th class="date-th">店舗名</th>
      <th class="date-th">獲得日</th>
      <th class="date-th">解約ステータス</th>
      <th class="date-th">解約申込（異動日）</th>
      <th class="date-th">契約種別</th>
      <th class="date-th">解約申込事業者</th>
      <th class="date-th">請求回数</th>
      <th class="date-th">詳細</th>
    </tr>
    <% @summits.each_with_index do |s, i| %>
    <tr>
      <td class="date-td"><%= i + 1 %></td>
      <% if s.summit_client.present? %>
      <td class="date-td">連携済</td>
      <% else %>
      <td class="date-td red">未携済</td>
      <% end %>
      <td class="date-td"><%= s.store_prop.name %></td>
      <td class="date-td"><%= s.date %></td>
      <td class="date-td"><%= s.summit_client.cancel_status rescue "" %></td>
      <td class="date-td"><%= s.summit_client.cancel rescue "" %></td>
      <td class="date-td"><%= s.contract_type %></td>
      <td class="date-td"><%= s.summit_client.cancel_app_company rescue "" %></td>
      <td class="date-td"><%= s.summit_billing_amounts.length rescue 0 %>回</td>
      <td class="date-td"><%= link_to "詳細", summit_path(s.id), "data-turbolinks": false, class: "link" %></td>
    </tr>
    <% end %>
  </table>
    <h2>◆<%= @month.year %>年：廃止件数</h2>
      <table>
        <tr>
          <th class="date-th">契約種別</th>
          <% cnt = 0 %>
          <% 12.times do  %>
          <th class="date-th"><%= cnt += 1 %>月</th>
          <% end %>
          <th class="date-th">合計</th>
        </tr>
        <tr>
          <td class="date-td">従量電灯</td>
          <% cnt = 1 %>
          <% metered_sum = 0 %>
          <% 12.times do %>
          <% if @metered_month_group[cnt].nil? %>
            <td class="date-td">0</td>
          <% else %>
            <td class="date-td"><%= @metered_month_group[cnt] %></td>
            <% metered_sum += @metered_month_group[cnt] %>
          <% end %>
          <% cnt += 1 %>
          <% end %>
          <td class="date-td"><%= metered_sum %></td>
        </tr>
        <tr>
          <td class="date-td">低圧電力</td>
          <% cnt = 1 %>
          <% low_voltage_sum = 0 %>
          <% 12.times do %>
          <% if @low_voltage_month_group[cnt].nil? %>
            <td class="date-td">0</td>
          <% else %>
            <td class="date-td"><%= @low_voltage_month_group[cnt] %></td>
            <% low_voltage_sum += @low_voltage_month_group[cnt] %>
          <% end %>
          <% cnt += 1 %>
          <% end %>
          <td class="date-td"><%= low_voltage_sum %></td>
        </tr>
      </table>
</div>