config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'results#index'
  resources :store_props do 
    collection { post :import }
    collection { get :export }
  end 

  resources :summit_clients, only: [:index, :show] do
    collection { post :import }
    collection { delete :all_delete }
  end

  resources :summits, expect: [:new, :create] do 
    collection { post :import }
    collection { post :import_price }
    collection { get :sw_error }
    collection { get :cancel }
    collection { delete :not_share_delete }
  end

  resources :summit_customer_props do 
    collection { post :import}
  end 

  resources :summit_error_histories do 
    collection { post :import }
  end 

  resources :summit_billing_amounts do 
    collection { post :import }
  end 

  resources :summit_date_progresses, only: [:index] do 
    collection {get :base}
  end 

  resources :summit_date_progresses, only: :show,param: :user_id


  resources :pranesses, expect: [:new, :create] do 
    collection { 
      post :import 
      get :simplified_chart
      get :not_payment
    }
  end 

  resources :payment_pranesses do 
    collection { 
      post :import 
      get :year_profit
      get :year_valuation
      get :not_payment
    }
  end 

  get "year_profit_price", to: "payment_pranesses#year_profit_price", as: "year_profit_price"
  get "year_profit_len", to: "payment_pranesses#year_profit_len", as: "year_profit_len"
  get "year_val_price", to: "payment_pranesses#year_val_price", as: "year_val_price"
  get "year_val_len", to: "payment_pranesses#year_val_len", as: "year_val_len"

  resources :praness_options do 
    collection {
      post :import 
    }
  end 

  resources :dmers do 
    collection { post :import }
    collection { get :index_export }
    collection { get :export }
    collection { get :simple_conf }
    collection { get :simple_conf_year }
    collection { get :deficiency }
  end 
  
  resources :stocks do 
    collection { post :import }
    resources :stock_histories
    resources :return_histories
  end 

  resources :aupays, expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :paypays, expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :airpays do
    collection { 
      post :import 
      get :simple_conf 
    }
  end
  
  resources :stock_histories, only: [:destroy]
  resources :return_histories, only: [:destroy]
  
  resources :pandas, expect: [:new, :create] do 
    collection {post :import}
  end 

  resources :users do 
    collection {post :comment_new}
    collection {put :comment_update}
  end

  resources :shifts,expect: [:show] do 
    collection do
      post :update_month
      delete :delete_month
      get :cashless
    end
  end 

  resources :shifts, only: :show,param: :user_id

  resources :panda_profits, only: :index

  resources :results,expect: [:show]  do 
    get 'result_cashes/new'
    post 'result_cashes/create'
    get 'result_types/new'
    post 'result_types/create'
    get 'result_casas/new'
    get 'result_summits/new'
    post 'result_summits/create'
    get 'type_reference_values/new'
    post 'type_reference_values/create'
    collection { 
      post :import 
      get :export
      get :date_progress
      get :monthly_progress
      get :ranking
      get :gross_profit
      get :profit
      get :base_profit
      get :daily_report
      get :dup_index
      post :comment_new
      put :comment_update
      get :out_come
      get :base_productivity
      get :team_productivity
      get :person_productivity
      get :product_status
      get :slmt_list
      get :deficiency
      get :inc_or_dec
      get :valuation_list
    }
  end
  resources :type_reference_values, only: [:edit, :update]

  resources :result_types do 
    resources :deal_attributes do
      collection do
        get :edit_all
        patch :update_all
      end
    end
end

  resources :results, only: :show, param: :result_id
  get "date_fin/:id", to: "results#date_fin", as: "date_fin"
  get "weekly_fin/:id", to: "results#weekly_fin", as: "weekly_fin"
  get "out_val/:id", to: "results#out_val", as: "out_val"
  get "out_val_all/:id", to: "results#out_val_all", as: "out_val_all"
  get "out_val_type/:id", to: "results#out_val_type", as: "out_val_type"
  get "store_val/:id", to: "results#store_val", as: "store_val"
  get "store_val_all/:id", to: "results#store_val_all", as: "store_val_all"
  get "visit_type_val/:id", to: "results#visit_type_val", as: "visit_type_val"

  get "monthly_get", to: "results#monthly_get", as: "monthly_get"
  get "monthly_get_base", to: "results#monthly_get_base", as: "monthly_get_base"
  get "sales_and_def", to: "results#sales_and_def", as: "sales_and_def"
  get "user_list", to: "results#user_list", as: "user_list"
  
  
  resources :results_base_valuations, only: :index
  get "valuation", to: "results_base_valuations#valuation", as: "valuation"
  get "standard_val", to: "results_base_valuations#standard_val", as: "standard_val"
  get "productivity", to: "results_base_valuations#productivity", as: "productivity"
  get "current_result", to: "results_base_valuations#current_result", as: "current_result"


  resources :ojts, only: :index do 
    collection { get :export }
    collection { get :index_export }
    collection { get :summary_export }
  end 
  resources :ojts, only: :show, param: :result_id

  resources :result_cashes do 
    collection { post :import}
  end
  resources :result_casas, expect: [:new, :create]
  resources :result_summits, expect: :show do 
    collection { get :base_profit }
    collection { get :person_data }
    collection { get :repeal_data }
    collection { get :sw_error_data }
    collection { get :error_history_data }
    collection { get :customer_prop_data }
    collection { get :billing_data }
    collection { get :prediction_data }
  end 
  resources :result_summits, only: :show,param: :user_id
  
  resources :n_results do 
    collection { post :import }
  end  

  resources :products
  
  resources :display_periods
  
  resources :trouble_ns do 
    collection { post :import }
  end

  resources :rakuten_casas ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :trouble_sses ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :st_insurances ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :rakuten_pays do 
    collection { 
      post :import
      get :index_export 
      get :deficiency
      get :deficiency_new
      get :simple_conf
      get :simple_conf_year
    }
  end 

  resources :error_pages
  
  resources :costs 

  resources :product_checkers, only: [:index]
  resources :product_tests, only: [:index]
  
  resources :result_sales, only: [:index] do 
    collection { post :import }
  end 

  resources :comments

  resources :def_respondings, only: [:index]
  
  resources :settlements, only: [:index]
  resources :other_products
  resources :dmer_stocks
  resources :product_targets
  resources :demaekans, only: [:index] do 
    collection {post :import}
  end 

  resources :profits, only: [:index] do 
    collection {get :sum_export}
    collection {get :index_export}
    collection {get :profit_export_by_spreadsheet}
    collection {get :product_export_by_spreadsheet}
  end
  # get 'profits', to: 'profits#index' do 
  #   collection {get :sum_export}
  # end 

  resources :calc_periods do 
    collection {
      get :cash_csv_export
      get :cash_valuation_csv_export
      get :weekly_data
    }
  end 

  get "val_users", to: "calc_periods#val_users", as: "val_users"

  
  resources :dmer_date_progresses do 
    collection {get :progress_create}
    collection {get :csv_export}
    collection {get :date_destroy}
  end 
  
  resources :aupay_date_progresses do 
    collection {get :progress_create}
    collection {get :csv_export}
    collection {get :date_destroy}
  end 

  resources :paypay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :rakuten_pay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end

  resources :airpay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :demaekan_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :austicker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :dmersticker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :airpaysticker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :cash_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :itsses do 
    collection {post :import}
  end 

  resources :itss_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :usen_pay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  
  resources :other_product_date_progresses, only: [:index] do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :airpay_stickers do 
    collection {post :import}
    collection {get :date_destroy}
  end 


  resources :payment_cashes 
  resources :payment_dmers do 
    collection { 
      post :import
      get :not_payment
      get :conf_index
      get :result1
      get :result2
      get :result3
    }
  end 

  resources :payment_dmer_senbais do 
    collection { 
      post :import
      get :not_payment
      get :conf_index
      get :result
    }
  end 

  resources :payment_rakuten_pays do 
    collection { 
      post :import
      get :not_payment
      get :conf_index

app/views/user_parts/_deficiency.html.erb
<h2>不備リスト</h2>
<table class="out-tb">
  <thead>
    <tr>
      <th class="valuation-th">商材</th>
      <th class="valuation-th">店舗名</th>
      <th class="valuation-th">商流</th>
      <th class="valuation-th">獲得者</th>
      <th class="valuation-th">獲得日</th>
      <th class="valuation-th-remarks">不備内容</th>
      <th class="valuation-th">詳細</th>
      <th class="valuation-th">対応日</th>
      <th class="valuation-th">対応状況</th>
      <th class="valuation-th">対応者</th>
      <th class="valuation-th">対応メモ</th>
      <th class="valuation-th"></th>
    </tr>
  </thead>
  <tbody>
    <% @dmers_def.each do |dmer| %>
    <% comment = dmer.store_prop.comments.where(product: "dメル").where(content: "不備").first %>
    <% if comment.present? && (comment.status == "対応済" || comment.status == "不可") %>
    <tr style="background-color: gray">
    <% else %>
    <tr>
    <% end %>
      <td class="valuation-td">dメル</td>
      <td class="valuation-td"><%= dmer.store_prop.name %></td>
      <td class="valuation-td"><%= dmer.client %></td>
      <td class="valuation-td"><%= dmer.user.name %></td>
      <td class="valuation-td"><%= dmer.date %></td>
      <td class="valuation-td-remarks"><%= dmer.deficiency_remarks %></td>
      <td class="valuation-td"><%= link_to "詳細" ,dmer_path(dmer.id) %></td>
      <%# コメント %>
      <% if comment.present? %>
      <td class="valuation-td"><%= dmer.store_prop.comments.where(content: "不備").first.request %></td>
      <td class="valuation-td"><%= dmer.store_prop.comments.where(content: "不備").first.status %></td>
      <td class="valuation-td"><%= dmer.store_prop.comments.where(content: "不備").first.ball %></td>
      <td class="valuation-td"><%= dmer.store_prop.comments.where(content: "不備").first.request_show %></td>
      <td class="valuation-td"><%= link_to "編集" ,edit_comment_path(dmer.store_prop.comments.where(content: "不備").first.id), class: "link" %></td>
      <% else %>
      <%= form_with(url: comment_new_results_path,data: {remote: false}) do |f| %>
      <%= f.hidden_field :store_prop_id, value: dmer.store_prop.id %>
      <%= f.hidden_field :product, value: "dメル" %>
      <%= f.hidden_field :content, value: "不備" %>
      <td class="valuation-td"><%= f.date_field :request, value: Date.today, class: "input" %></td>
      <td class="valuation-td">
        <%= 
          f.select :status, {
            "対応中": "対応中",
            "対応済": "対応済",
            "不可": "不可" 
          }, {include_blank: true}, {class: "input"}
        %>
      </td>
      <td class="valuation-td">
        <%= 
          f.select :ball, {
            "営業": "営業",
            "管理": "管理",
          }, {include_blank: true}, {class: "input"}
        %>
      </td>
      <td class="valuation-td"><%= f.text_field :request_show, class: "input" %></td>
      <td class="valuation-td"><%= f.submit "登録", class: "comment-btn" %></td>
      <% end %>
    <% end %>
    </tr>
    <% end %>
    <% @aupays_def.each do |aupay| %>
    <% comment = aupay.store_prop.comments.where(product: "auPay").where(content: "不備").first %>
    <% if comment.present? && (comment.status == "対応済" || comment.status == "不可") %>
    <tr style="background-color: gray">
    <% else %>
    <tr>
    <% end %>
      <td class="valuation-td">auPay</td>
      <td class="valuation-td"><%= aupay.store_prop.name %></td>
      <td class="valuation-td"><%= aupay.client %></td>
      <td class="valuation-td"><%= aupay.user.name %></td>
      <td class="valuation-td"><%= aupay.date %></td>
      <td class="valuation-td-remarks"><%= aupay.deficiency_remarks %></td>
      <td class="valuation-td"><%= link_to "詳細" ,aupay_path(aupay.id) %></td>
  <% if comment.present? %>
      <td class="valuation-td"><%= aupay.store_prop.comments.where(content: "不備").first.request %></td>
      <td class="valuation-td"><%= aupay.store_prop.comments.where(content: "不備").first.status %></td>
      <td class="valuation-td"><%= aupay.store_prop.comments.where(content: "不備").first.ball %></td>
      <td class="valuation-td"><%= aupay.store_prop.comments.where(content: "不備").first.request_show %></td>
      <td class="valuation-td"><%= link_to "編集" ,edit_comment_path(aupay.store_prop.comments.where(content: "不備").first.id), class: "link" %></td>
      <% else %>
      <%= form_with(url: comment_new_results_path,data: {remote: false}) do |f| %>
      <%= f.hidden_field :store_prop_id, value: aupay.store_prop.id %>
      <%= f.hidden_field :product, value: "auPay" %>
      <%= f.hidden_field :content, value: "不備" %>
      <td class="valuation-td"><%= f.date_field :request, value: Date.today, class: "input" %></td>
      <td class="valuation-td">
        <%= 
          f.select :status, {
            "対応中": "対応中",
            "対応済": "対応済",
            "不可": "不可" 
          }, {include_blank: true}, {class: "input"}
        %>
      </td>
      <td class="valuation-td">
        <%= 
          f.select :ball, {
            "営業": "営業",
            "管理": "管理",
          }, {include_blank: true}, {class: "input"}
        %>
      </td>
      <td class="valuation-td"><%= f.text_field :request_show, class: "input" %></td>
      <td class="valuation-td"><%= f.submit "登録", class: "comment-btn" %></td>
      <% end %>
    <% end %>
    </tr>
    <% end %>
    <% @rakuten_pays_def.each do |rakuten_pay| %>
    <% comment = rakuten_pay.store_prop.comments.where(product: "楽天ペイ").where(content: "不備").first %>
    <% if comment.present? && (comment.status == "対応済" || comment.status == "不可") %>
    <tr style="background-color: gray">
    <% else %>
    <tr>
    <% end %>
      <td class="valuation-td">楽天ペイ</td>
      <td class="valuation-td"><%= rakuten_pay.store_prop.name %></td>
      <td class="valuation-td"><%= rakuten_pay.client %></td>
      <td class="valuation-td"><%= rakuten_pay.user.name %></td>
      <td class="valuation-td"><%= rakuten_pay.date %></td>
      <td class="valuation-td-remarks"><%= rakuten_pay.deficiency_info %></td>
      <td class="valuation-td"><%= link_to "詳細" ,rakuten_pay_path(rakuten_pay.id) %></td>
<% if comment.present? %>
      <td class="valuation-td"><%= rakuten_pay.store_prop.comments.where(content: "不備").first.request %></td>
      <td class="valuation-td"><%= rakuten_pay.store_prop.comments.where(content: "不備").first.status %></td>
      <td class="valuation-td"><%= rakuten_pay.store_prop.comments.where(content: "不備").first.ball %></td>
      <td class="valuation-td"><%= rakuten_pay.store_prop.comments.where(content: "不備").first.request_show %></td>
      <td class="valuation-td"><%= link_to "編集" ,edit_comment_path(rakuten_pay.store_prop.comments.where(content: "不備").first.id), class: "link" %></td>
      <% else %>
      <%= form_with(url: comment_new_results_path,data: {remote: false}) do |f| %>
      <%= f.hidden_field :store_prop_id, value: rakuten_pay.store_prop.id %>
      <%= f.hidden_field :product, value: "楽天ペイ" %>
      <%= f.hidden_field :content, value: "不備" %>
      <td class="valuation-td"><%= f.date_field :request, value: Date.today, class: "input" %></td>
      <td class="valuation-td">
        <%= 
          f.select :status, {
            "対応中": "対応中",
            "対応済": "対応済",
            "不可": "不可" 
          }, {include_blank: true}, {class: "input"}
        %>
      </td>
      <td class="valuation-td">
        <%= 
          f.select :ball, {
            "営業": "営業",
            "管理": "管理",
          }, {include_blank: true}, {class: "input"}
        %>
      </td>
      <td class="valuation-td"><%= f.text_field :request_show, class: "input" %></td>
      <td class="valuation-td"><%= f.submit "登録", class: "comment-btn" %></td>
      <% end %>
    <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/user_parts/_slmt.html.erb
<h2>決済リスト</h2>
<table>
  <tr>
    <th class="valuation-th">dメル</th>
    <th class="valuation-th">auPay</th>
  </tr>
  <tr>
    <td class="valuation-td"><%= 
            @slmts.where.not(dmer: {id: nil})
            .where(dmer: {user_id: @user.id}) 
            .where.not(dmer: {industry_status: "×"}) 
            .where.not(dmer: {industry_status: "NG"}) 
            .where.not(dmer: {industry_status: "要確認"}) 
            .where(dmer: {status: "審査OK"}) 
            .where.not(dmer: {status_settlement: "完了"}) 
            .where.not(dmer: {status_settlement: "期限切れ"}).length 
    %></td>
    <td class="valuation-td"><%= 
            @slmts.where.not(aupay: {id: nil})
            .where(aupay: {user_id: @user.id})
            .where(aupay: {status: "審査通過"})
            .where.not(aupay: {status_settlement: "完了"}) 
            .where.not(aupay: {status_settlement: "期限切れ"}).length 
    %></td>
  </tr>
</table>
<table class="out-tb">
  <thead>
    <tr>
      <th class="valuation-th">商材</th>
      <th class="valuation-th">店舗名</th>
      <th class="valuation-th">商流</th>
      <th class="valuation-th">獲得者</th>
      <th class="valuation-th">獲得日</th>
      <th class="valuation-th">決済ステータス</th>
      <th class="valuation-th">決済期限</th>
      <th class="valuation-th-remarks">不備内容</th>
      <th class="valuation-th">商材詳細</th>
      <th class="valuation-th">店舗詳細</th>
      <th class="valuation-th">対応状況</th>
      <th class="valuation-th">対応メモ</th>
      <th class="valuation-th"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @slmts.each do |store| %>
      
      <%# aupay_comment = @comments.find_by(store_prop_id: store.id, product: "auPay", content: "決済") %>
      <%# dメル決済 %>
      <% if 
        store.dmer.present? && 
        store.dmer.user_id == @user.id &&
        store.dmer.status_settlement != "完了" && 
        store.dmer.status_settlement != "期限切れ" &&
        store.dmer.status == "審査OK" &&
        store.dmer.industry_status != "×" &&
        store.dmer.industry_status != "要確認" &&
        store.dmer.industry_status != "NG"
      %>
      <td class="valuation-td">dメル</td>
      <td class="valuation-td"><%= store.name %></td>
      <td class="valuation-td"><%= store.dmer.client %></td>
      <td class="valuation-td"><%= store.dmer.user.name %></td>
      <td class="valuation-td"><%= store.dmer.date %></td>
      <td class="valuation-td"><%= store.dmer.status_settlement %></td>
      <td class="valuation-td"><%= store.dmer.settlement_deadline %></td>
      <td class="valuation-td-remarks"><%= store.dmer.deficiency_remarks_settlement %></td>
      <td class="valuation-td" ><%= link_to "dメル詳細", dmer_path(store.dmer.id),class: "link" %></td>
      <td class="valuation-td" ><%= link_to "店舗詳細", store_prop_path(store.id),class: "link" %></td>
      <%# コメント機能 %>
        <% dmer_comment = store.comments.where(product: "dメル").where(content: "決済").first %>
        <% if dmer_comment.present? %>
        <% comment = store.comments.where(content: "決済").first %>
        <td class="valuation-td"><%= comment.status %></td>
        <td class="valuation-td"><%= comment.request_show %></td>
        <td class="valuation-td"><%= link_to "編集" ,edit_comment_path(comment.id), class: "link" %></td>
        <% else %>
        <%= form_with(url: comment_new_results_path,data: {remote: false}) do |f| %>
        <%= f.hidden_field :store_prop_id, value: store.id %>
        <%= f.hidden_field :product, value: "dメル" %>
        <%= f.hidden_field :content, value: "決済" %>
        <%= f.hidden_field :ball, value: "営業" %>
        <%= f.hidden_field :request, value: Date.today %>
        <td class="valuation-td">
          <%= 
            f.select :status, {
              "対応中": "対応中",
              "対応済": "対応済",
              "不可": "不可" 
            }, {}, {class: "input"}
          %>
        </td>
        <td class="valuation-td"><%= f.text_field :request_show, class: "input" %></td>
        <td class="valuation-td"><%= f.submit "登録", class: "comment-btn","data-turbolinks": false %></td>
        <%# link_to "登録", new_comment_path(store_id: store.id,product: "dメル",content: "決済"),class: "comment-btn","data-turbolinks": false %>
        <% end %>
        <% end %>
      <%# /コメント機能 %>
      <% end %>
      </tr>
      <%# aupay決済 %>
      <% if 
        store.aupay.present? && 
        store.aupay.user_id == @user.id &&
        store.aupay.status_settlement != "完了" && 
        store.aupay.status_settlement != "期限切れ" &&
        store.aupay.status == "審査通過" &&
      %>
      <tr>
      <td class="valuation-td">auPay</td>
      <td class="valuation-td"><%= store.name %></td>
      <td class="valuation-td"><%= store.aupay.client %></td>
      <td class="valuation-td"><%= store.aupay.user.name %></td>
      <td class="valuation-td"><%= store.aupay.date %></td>
      <td class="valuation-td"><%= store.aupay.status_settlement %></td>
      <td class="valuation-td"><%= store.aupay.settlement_deadline %></td>
      <td class="valuation-td-remarks"><%= store.aupay.deficiency_remarks_settlement %></td>
      <td class="valuation-td" ><%= link_to "auPay詳細", aupay_path(store.aupay.id),class: "link" %></td>
      <td class="valuation-td" ><%= link_to "店舗詳細", store_prop_path(store.id),class: "link" %></td>
      <%# コメント機能 %>
        <% aupay_comment = store.comments.where(product: "auPay").where(content: "決済").first %>
        <% if aupay_comment.present? %>
        <% comment = store.comments.where(content: "決済").first %>
        <td class="valuation-td"><%= comment.status %></td>
        <td class="valuation-td"><%= comment.request_show %></td>
        <td class="valuation-td"><%= link_to "編集" ,edit_comment_path(comment.id), class: "link" %></td>
        <% else %>
        <%= form_with(url: comment_new_results_path,data: {remote: false}) do |f| %>
        <%= f.hidden_field :store_prop_id, value: store.id %>
        <%= f.hidden_field :product, value: "auPay" %>
        <%= f.hidden_field :content, value: "決済" %>
        <%= f.hidden_field :ball, value: "営業" %>
        <%= f.hidden_field :request, value: Date.today %>
        <td class="valuation-td">
          <%= 
            f.select :status, {
              "対応中": "対応中",
              "対応済": "対応済",
              "不可": "不可" 
            }, {}, {class: "input"}
          %>
        </td>
        <td class="valuation-td"><%= f.text_field :request_show, class: "input" %></td>
        <td class="valuation-td"><%= f.submit "登録", class: "comment-btn","data-turbolinks": false %></td>
        <% end %>
        <% end %>
      <%# /コメント機能 %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>