config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'results#index'
  resources :store_props do 
    collection { post :import }
    collection { get :export }
  end 

  resources :summit_clients, only: [:index, :show] do
    collection { post :import }
    collection { delete :all_delete }
  end

  resources :summits, expect: [:new, :create] do 
    collection { post :import }
    collection { post :import_price }
    collection { get :sw_error }
    collection { get :cancel }
    collection { delete :not_share_delete }
  end

  resources :summit_customer_props do 
    collection { post :import}
  end 

  resources :summit_error_histories do 
    collection { post :import }
  end 

  resources :summit_billing_amounts do 
    collection { post :import }
  end 

  resources :summit_date_progresses, only: [:index] do 
    collection {get :base}
  end 

  resources :summit_date_progresses, only: :show,param: :user_id


  resources :pranesses, expect: [:new, :create] do 
    collection { 
      post :import 
      get :simplified_chart
      get :not_payment
    }
  end 

  resources :payment_pranesses do 
    collection { 
      post :import 
      get :year_profit
      get :year_valuation
      get :not_payment
    }
  end 

  get "year_profit_price", to: "payment_pranesses#year_profit_price", as: "year_profit_price"
  get "year_profit_len", to: "payment_pranesses#year_profit_len", as: "year_profit_len"
  get "year_val_price", to: "payment_pranesses#year_val_price", as: "year_val_price"
  get "year_val_len", to: "payment_pranesses#year_val_len", as: "year_val_len"

  resources :praness_options do 
    collection {
      post :import 
    }
  end 

  resources :dmers do 
    collection { post :import }
    collection { get :index_export }
    collection { get :export }
    collection { get :simple_conf }
    collection { get :simple_conf_year }
    collection { get :deficiency }
  end 
  
  resources :stocks do 
    collection { post :import }
    resources :stock_histories
    resources :return_histories
  end 

  resources :aupays, expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :paypays, expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :airpays do
    collection { 
      post :import 
      get :simple_conf 
    }
  end
  
  resources :stock_histories, only: [:destroy]
  resources :return_histories, only: [:destroy]
  
  resources :pandas, expect: [:new, :create] do 
    collection {post :import}
  end 

  resources :users do 
    collection {post :comment_new}
    collection {put :comment_update}
  end

  resources :shifts,expect: [:show] do 
    collection do
      post :update_month
      delete :delete_month
      get :cashless
    end
  end 

  resources :shifts, only: :show,param: :user_id

  resources :panda_profits, only: :index

  resources :results,expect: [:show]  do 
    get 'result_cashes/new'
    post 'result_cashes/create'
    get 'result_types/new'
    post 'result_types/create'
    get 'result_casas/new'
    get 'result_summits/new'
    post 'result_summits/create'
    get 'type_reference_values/new'
    post 'type_reference_values/create'
    collection { 
      post :import 
      get :export
      get :date_progress
      get :monthly_progress
      get :ranking
      get :gross_profit
      get :profit
      get :base_profit
      get :daily_report
      get :dup_index
      post :comment_new
      put :comment_update
      get :out_come
      get :base_productivity
      get :team_productivity
      get :person_productivity
      get :product_status
      get :slmt_list
      get :deficiency
      get :inc_or_dec
      get :valuation_list
    }
  end
  resources :type_reference_values, only: [:edit, :update]

  resources :result_types do 
    resources :deal_attributes do
      collection do
        get :edit_all
        patch :update_all
      end
    end
end

  resources :results, only: :show, param: :result_id
  get "date_fin/:id", to: "results#date_fin", as: "date_fin"
  get "weekly_fin/:id", to: "results#weekly_fin", as: "weekly_fin"
  get "out_val/:id", to: "results#out_val", as: "out_val"
  get "out_val_all/:id", to: "results#out_val_all", as: "out_val_all"
  get "out_val_type/:id", to: "results#out_val_type", as: "out_val_type"
  get "store_val/:id", to: "results#store_val", as: "store_val"
  get "store_val_all/:id", to: "results#store_val_all", as: "store_val_all"
  get "visit_type_val/:id", to: "results#visit_type_val", as: "visit_type_val"

  get "monthly_get", to: "results#monthly_get", as: "monthly_get"
  get "monthly_get_base", to: "results#monthly_get_base", as: "monthly_get_base"
  get "sales_and_def", to: "results#sales_and_def", as: "sales_and_def"
  get "user_list", to: "results#user_list", as: "user_list"
  
  
  resources :results_base_valuations, only: :index
  get "valuation", to: "results_base_valuations#valuation", as: "valuation"
  get "standard_val", to: "results_base_valuations#standard_val", as: "standard_val"
  get "productivity", to: "results_base_valuations#productivity", as: "productivity"
  get "current_result", to: "results_base_valuations#current_result", as: "current_result"


  resources :ojts, only: :index do 
    collection { get :export }
    collection { get :index_export }
    collection { get :summary_export }
  end 
  resources :ojts, only: :show, param: :result_id

  resources :result_cashes do 
    collection { post :import}
  end
  resources :result_casas, expect: [:new, :create]
  resources :result_summits, expect: :show do 
    collection { get :base_profit }
    collection { get :person_data }
    collection { get :repeal_data }
    collection { get :sw_error_data }
    collection { get :error_history_data }
    collection { get :customer_prop_data }
    collection { get :billing_data }
    collection { get :prediction_data }
  end 
  resources :result_summits, only: :show,param: :user_id
  
  resources :n_results do 
    collection { post :import }
  end  

  resources :products
  
  resources :display_periods
  
  resources :trouble_ns do 
    collection { post :import }
  end

  resources :rakuten_casas ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :trouble_sses ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :st_insurances ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :rakuten_pays do 
    collection { 
      post :import
      get :index_export 
      get :deficiency
      get :deficiency_new
      get :simple_conf
      get :simple_conf_year
    }
  end 

  resources :error_pages
  
  resources :costs 

  resources :product_checkers, only: [:index]
  resources :product_tests, only: [:index]
  
  resources :result_sales, only: [:index] do 
    collection { post :import }
  end 

  resources :comments

  resources :def_respondings, only: [:index]
  
  resources :settlements, only: [:index]
  resources :other_products
  resources :dmer_stocks
  resources :product_targets
  resources :demaekans, only: [:index] do 
    collection {post :import}
  end 

  resources :profits, only: [:index] do 
    collection {get :sum_export}
    collection {get :index_export}
    collection {get :profit_export_by_spreadsheet}
    collection {get :product_export_by_spreadsheet}
  end
  # get 'profits', to: 'profits#index' do 
  #   collection {get :sum_export}
  # end 

  resources :calc_periods do 
    collection {
      get :cash_csv_export
      get :cash_valuation_csv_export
      get :weekly_data
    }
  end 

  get "val_users", to: "calc_periods#val_users", as: "val_users"

  
  resources :dmer_date_progresses do 
    collection {get :progress_create}
    collection {get :csv_export}
    collection {get :date_destroy}
  end 
  
  resources :aupay_date_progresses do 
    collection {get :progress_create}
    collection {get :csv_export}
    collection {get :date_destroy}
  end 

  resources :paypay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :rakuten_pay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end

  resources :airpay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :demaekan_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :austicker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :dmersticker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :airpaysticker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :cash_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :itsses do 
    collection {post :import}
  end 

  resources :itss_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :usen_pay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  
  resources :other_product_date_progresses, only: [:index] do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :airpay_stickers do 
    collection {post :import}
    collection {get :date_destroy}
  end 


  resources :payment_cashes 
  resources :payment_dmers do 
    collection { 
      post :import
      get :not_payment
      get :conf_index
      get :result1
      get :result2
      get :result3
    }
  end 

  resources :payment_dmer_senbais do 
    collection { 
      post :import
      get :not_payment
      get :conf_index
      get :result
    }
  end 

  resources :payment_rakuten_pays do 
    collection { 
      post :import
      get :not_payment
      get :conf_index

app/controllers/results_base_valuations_controller.rb
class ResultsBaseValuationsController < ApplicationController
  # 拠点別利益表
  before_action :set_data

  def index #メインページ

  end 

  def valuation 
    render partial: "valuation", locals: {} # を遅延ロード
  end 
  def standard_val 
    render partial: "standard_val", locals: {} # を遅延ロード
  end 
  def productivity 
    render partial: "productivity", locals: {} # を遅延ロード
  end 
  def current_result 
    render partial: "current_result", locals: {} # を遅延ロード
  end 

  private 
  def set_data
    @month = params[:month] ? Time.parse(params[:month]) : Date.today
    @base = params[:base]
    @results = Result.includes(:user).where(user: {base: @base}).where(date: @month.all_month)
    @users = User.where(base: @base).where(base_sub: "キャッシュレス").where.not(position: "退職").order("users.position_sub ASC").order("users.id ASC")
    @cash_date_progress = CashDateProgress.includes(:user).where(date: @month.all_month).where(user: {base: @base}).where(user: {base_sub: "キャッシュレス"}).where.not(user: {position: "退職"})
    @cash_date_progress = @cash_date_progress.where(date: @cash_date_progress.maximum(:date)).where(create_date: @cash_date_progress.maximum(:create_date))
    @dmer_date_progress = DmerDateProgress.includes(:user).where(date: @month.all_month).where(user: {base: @base}).where(user: {base_sub: "キャッシュレス"}).where.not(user: {position: "退職"})
    @dmer_date_progress = @dmer_date_progress.where(date: @dmer_date_progress.maximum(:date)).where(create_date: @dmer_date_progress.maximum(:create_date))
    @dmer_senbai_date_progress = DmerSenbaiDateProgress.includes(:user).where(date: @month.all_month).where(user: {base: @base}).where(user: {base_sub: "キャッシュレス"}).where.not(user: {position: "退職"})
    @dmer_senbai_date_progress = @dmer_senbai_date_progress.where(date: @dmer_senbai_date_progress.maximum(:date)).where(create_date: @dmer_senbai_date_progress.maximum(:create_date))
    @aupay_date_progress = AupayDateProgress.includes(:user).where(date: @month.all_month).where(user: {base: @base}).where(user: {base_sub: "キャッシュレス"}).where.not(user: {position: "退職"})
    @aupay_date_progress = @aupay_date_progress.where(date: @aupay_date_progress.maximum(:date)).where(create_date: @aupay_date_progress.maximum(:create_date))
    @rakuten_pay_date_progress = RakutenPayDateProgress.includes(:user).where(date: @month.all_month).where(user: {base: @base}).where(user: {base_sub: "キャッシュレス"}).where.not(user: {position: "退職"})
    @rakuten_pay_date_progress = @rakuten_pay_date_progress.where(date: @rakuten_pay_date_progress.maximum(:date)).where(create_date: @rakuten_pay_date_progress.maximum(:create_date))
    @airpay_date_progress = AirpayDateProgress.includes(:user).where(date: @month.all_month).where(user: {base: @base}).where(user: {base_sub: "キャッシュレス"}).where.not(user: {position: "退職"})
    @airpay_date_progress = @airpay_date_progress.where(date: @airpay_date_progress.maximum(:date)).where(create_date: @airpay_date_progress.maximum(:create_date))
    @paypay_date_progress = PaypayDateProgress.includes(:user).where(date: @month.all_month).where(user: {base: @base}).where(user: {base_sub: "キャッシュレス"}).where.not(user: {position: "退職"})
    @paypay_date_progress = @paypay_date_progress.where(date: @paypay_date_progress.maximum(:date)).where(create_date: @paypay_date_progress.maximum(:create_date))
    @airpaysticker_date_progress = AirpaystickerDateProgress.includes(:user).where(date: @month.all_month).where(user: {base: @base}).where(user: {base_sub: "キャッシュレス"}).where.not(user: {position: "退職"})
    @airpaysticker_date_progress = @airpaysticker_date_progress.where(date: @airpaysticker_date_progress.maximum(:date)).where(create_date: @airpaysticker_date_progress.maximum(:create_date))
    
    @usen_pay_date_progress = OtherProductDateProgress.includes(:user).where(product_name: "UsenPay").where(date: @month.all_month).where(user: {base: @base}).where(user: {base_sub: "キャッシュレス"}).where.not(user: {position: "退職"})
    @usen_pay_date_progress = @usen_pay_date_progress.where(date: @usen_pay_date_progress.maximum(:date)).where(create_date: @usen_pay_date_progress.maximum(:create_date))
  end 
end

app/helpers/results_base_valuations_helper.rb
module ResultsBaseValuationsHelper
end

app/views/results_base_valuations/_current_result.html.erb
<h2>◆<%= @base %>現状成果になった件数</h2>
<table class="progress-tb">
  <tr>
    <th class="product-th1" colspan="2">基本情報</th>
    <th class="product-th1" colspan="12">成果</th>
  </tr>
  <tr>
    <th class="progress-th2">氏名</th>
    <th class="progress-th2">役職</th>
    <th class="progress-th2">dメル<br>（審査完了）</th>
    <th class="progress-th2">dメル<br>（決済+アクセプタンス）</th>
    <th class="progress-th2">dメル<br>（2回目決済）</th>
    <th class="progress-th2">auPay<br>（決済+アクセプタンス）</th>
    <th class="progress-th2">PayPay<br>（審査完了）</th>
    <th class="progress-th2">楽天ペイ<br>（獲得）</th>
    <th class="progress-th2">AirPay<br>（審査完了）</th>
    <th class="progress-th2">AirPayステッカー<br>（営業報告）</th>
  </tr>
  <% @users.each do |user| %>
  <tr class="progress-tr">
    <td class="progress-td"><%= user.name %></td>
    <td class="progress-td"><%= user.position_sub %></td>
    <td class="progress-td"><%= @dmer_date_progress.find_by(user_id: user.id).done_len.to_i rescue 0 %></td>
    <td class="progress-td"><%= @dmer_date_progress.find_by(user_id: user.id).result2_len.to_i rescue 0 %></td>
    <td class="progress-td"><%= @dmer_date_progress.find_by(user_id: user.id).result3_len.to_i rescue 0 %></td>
    <td class="progress-td"><%= @aupay_date_progress.find_by(user_id: user.id).result_len.to_i rescue 0 %></td>
    <td class="progress-td"><%= @paypay_date_progress.find_by(user_id: user.id).result_len.to_i rescue 0 %></td>
    <td class="progress-td"><%= @rakuten_pay_date_progress.find_by(user_id: user.id).valuation_current / 4000 rescue 0 %></td>
    <td class="progress-td"><%= @airpay_date_progress.find_by(user_id: user.id).result_len.to_i rescue 0 %></td>
    <td class="progress-td"><%= @airpaysticker_date_progress.find_by(user_id: user.id).get_len.to_i rescue 0 %></td>
  </tr>
  <% end %>
  <tr>
    <td class="difference-td" colspan="2">合計</td>
    <td class="difference-td"><%= @dmer_date_progress.sum(:done_len) rescue 0 %></td>
    <td class="difference-td"><%= @dmer_date_progress.sum(:result2_len) rescue 0 %></td>
    <td class="difference-td"><%= @dmer_date_progress.sum(:result3_len) rescue 0 %></td>
    <td class="difference-td"><%= @aupay_date_progress.sum(:result_len) rescue 0 %></td>
    <td class="difference-td"><%= @paypay_date_progress.sum(:result_len) rescue 0 %></td>
    <td class="difference-td"><%= @rakuten_pay_date_progress.sum(:valuation_current) / 4000 rescue 0 %></td>
    <td class="difference-td"><%= @airpay_date_progress.sum(:result_len) rescue 0 %></td>
    <td class="difference-td"><%= @airpaysticker_date_progress.sum(:get_len) rescue 0 %></td>
  </tr>
</table>

app/views/results_base_valuations/_productivity.html.erb
<h2>◆<%= @base %>生産性</h2>
<table class="progress-tb">
  <tr>
    <th class="product-th1" colspan="2">基本情報</th>
    <th class="product-th1" colspan="2">新規シフト</th>
    <th class="product-th1" colspan="4">dメル専売</th>
    <th class="product-th1" colspan="3">auPay</th>
    <th class="product-th1" colspan="3">UsenPay</th>
  </tr>
  <tr>
    <th class="progress-th2">氏名</th>
    <th class="progress-th2">役職</th>
    <th class="progress-th2">予定</th>
    <th class="progress-th2">消化</th>
    <th class="progress-th2">獲得Ave</th>
    <th class="progress-th2">獲得</th>
    <th class="progress-th2">不備・NG</th>
    <th class="progress-th2">獲得終着</th>
    <% 2.times do %>
    <th class="progress-th2">獲得Ave</th>
    <th class="progress-th2">獲得</th>
    <th class="progress-th2">獲得終着</th>
    <% end %>

  </tr>
  <% @users.each do |user| %>
  <tr class="progress-tr">
    <td class="progress-td"><%= user.name %></td>
    <td class="progress-td"><%= user.position_sub %></td>
    <td class="progress-td"><%= @cash_date_progress.find_by(user_id: user.id).shift_schedule rescue 0 %></td>
    <td class="progress-td"><%= @cash_date_progress.find_by(user_id: user.id).shift_digestion rescue 0 %></td>
    <td class="progress-td"><%= (@dmer_senbai_date_progress.find_by(user_id: user.id).fin_len.to_f / @dmer_senbai_date_progress.find_by(user_id: user.id).shift_schedule).round(1) rescue 0 %></td>
    <td class="progress-td"><%= @dmer_senbai_date_progress.find_by(user_id: user.id).get_len rescue 0 %></td>
    <td class="progress-td"><%= @dmer_senbai_date_progress.find_by(user_id: user.id).def_len rescue 0 %></td>
    <td class="progress-td"><%= @dmer_senbai_date_progress.find_by(user_id: user.id).fin_len rescue 0 %></td>
    <td class="progress-td"><%= (@aupay_date_progress.find_by(user_id: user.id).fin_len.to_f / @aupay_date_progress.find_by(user_id: user.id).shift_schedule).round(1) rescue 0 %></td>
    <td class="progress-td"><%= @aupay_date_progress.find_by(user_id: user.id).get_len rescue 0 %></td>
    <td class="progress-td"><%= @aupay_date_progress.find_by(user_id: user.id).fin_len rescue 0 %></td>
    <td class="progress-td"><%= (@usen_pay_date_progress.find_by(user_id: user.id).fin_len.to_f / @cash_date_progress.find_by(user_id: user.id).shift_schedule).round(1) rescue 0 %></td>
    <td class="progress-td"><%= @usen_pay_date_progress.find_by(user_id: user.id).get_len rescue 0 %></td>
    <td class="progress-td"><%= @usen_pay_date_progress.find_by(user_id: user.id).fin_len rescue 0 %></td>
  </tr>
  <% end %>
  <tr>
    <td class="difference-td" colspan="2">合計</td>
    <td class="difference-td"><%= @cash_date_progress.sum(:shift_schedule) rescue 0 %></td>
    <td class="difference-td"><%= @cash_date_progress.sum(:shift_digestion) rescue 0 %></td>
    <td class="difference-td"><%= (@dmer_senbai_date_progress.sum(:fin_len).to_f / @dmer_senbai_date_progress.sum(:shift_schedule)).round(1) rescue 0 %></td>
    <td class="difference-td"><%= @dmer_senbai_date_progress.sum(:get_len) rescue 0 %></td>
    <td class="difference-td"><%= @dmer_senbai_date_progress.sum(:def_len) rescue 0 %></td>
    <td class="difference-td"><%= @dmer_senbai_date_progress.sum(:fin_len) rescue 0 %></td>
    <td class="difference-td"><%= (@aupay_date_progress.sum(:fin_len).to_f / @aupay_date_progress.sum(:shift_schedule)).round(1) rescue 0 %></td>
    <td class="difference-td"><%= @aupay_date_progress.sum(:get_len) rescue 0 %></td>
    <td class="difference-td"><%= @aupay_date_progress.sum(:fin_len) rescue 0 %></td>
    <td class="difference-td"><%= (@usen_pay_date_progress.sum(:fin_len).to_f / @cash_date_progress.sum(:shift_schedule)).round(1) rescue 0 %></td>
    <td class="difference-td"><%= @usen_pay_date_progress.sum(:get_len) rescue 0 %></td>
    <td class="difference-td"><%= @usen_pay_date_progress.sum(:fin_len) rescue 0 %></td>
  </tr>
</table>

app/views/results_base_valuations/_valuation.html.erb
<%# 拠点別利益表の売上 %>
<h2>◆<%= @base %>売上（最終更新：<%= @cash_date_progress.maximum(:create_date) %>）</h2>
<table class="progress-tb">
  <tr>
    <th class="progress-th1" colspan="2">基本情報</th>
    <th class="progress-th1" colspan="2">合計シフト</th>
    <th class="progress-th1" colspan="2">新規シフト</th>
    <th class="progress-th1" colspan="2">決済シフト</th>
    <th class="progress-th1" colspan="3">評価売上</th>
  </tr>
  <tr>
    <th class="progress-th2">氏名</th>
    <th class="progress-th2">役職</th>
    <% 3.times do %>
    <th class="progress-th2">予定</th>
    <th class="progress-th2">消化</th>
    <% end %>
    <th class="progress-th2">Ave</th>
    <th class="progress-th2">現状売上</th>
    <th class="progress-th2">終着売上</th>
  </tr>
  <% @users.each do |user| %>
  <% shift_schedule = @dmer_date_progress.find_by(user_id: user.id).shift_schedule rescue 0 %>
  <% shift_digestion = @dmer_date_progress.find_by(user_id: user.id).shift_digestion rescue 0 %>
  <tr class="progress-tr">
    <td class="progress-td"><%= user.name %></td>
    <td class="progress-td"><%= user.position_sub %></td>
    <td class="progress-td"><%= @cash_date_progress.find_by(user_id: user.id).shift_schedule rescue 0 %></td>
    <td class="progress-td"><%= @cash_date_progress.find_by(user_id: user.id).shift_digestion rescue 0 %></td>
    <td class="progress-td"><%= shift_schedule %></td>
    <td class="progress-td"><%= shift_digestion %></td>
    <td class="progress-td"><%= @dmer_date_progress.find_by(user_id: user.id).shift_schedule_slmt rescue 0 %></td>
    <td class="progress-td"><%= @dmer_date_progress.find_by(user_id: user.id).shift_digestion_slmt rescue 0 %></td>
    <td class="progress-td"><%= (@cash_date_progress.find_by(user_id: user.id).valuation_fin.to_f / @cash_date_progress.find_by(user_id: user.id).shift_schedule).round().to_s(:delimited) rescue 0 %></td>
    <td class="progress-td"><%= @cash_date_progress.find_by(user_id: user.id).valuation_current.to_s(:delimited) rescue 0 %></td>
    <td class="progress-td"><%= @cash_date_progress.find_by(user_id: user.id).valuation_fin.to_s(:delimited) rescue 0 %></td>
  </tr>
  <% end %>
  <tr class=""> 
    <td class="difference-td" colspan="2">合計</td>
    <td class="difference-td"><%= @cash_date_progress.sum(:shift_schedule) rescue 0 %></td>
    <td class="difference-td"><%= @cash_date_progress.sum(:shift_digestion) rescue 0 %></td>
    <td class="difference-td"><%= @dmer_date_progress.sum(:shift_schedule) rescue 0 %></td>
    <td class="difference-td"><%= @dmer_date_progress.sum(:shift_digestion) rescue 0 %></td>
    <td class="difference-td"><%= @dmer_date_progress.sum(:shift_schedule_slmt) rescue 0 %></td>
    <td class="difference-td"><%= @dmer_date_progress.sum(:shift_digestion_slmt) rescue 0 %></td>
    <td class="difference-td"><%= (@cash_date_progress.sum(:valuation_fin).to_f / @cash_date_progress.sum(:shift_schedule)).round().to_s(:delimited) rescue 0 %></td>
    <td class="difference-td"><%= @cash_date_progress.sum(:valuation_current).to_s(:delimited) rescue 0 %></td>
    <td class="difference-td"><%= @cash_date_progress.sum(:valuation_fin).to_s(:delimited) rescue 0 %></td>
  </tr>
</table>

app/views/results_base_valuations/index.html.erb
<% days = ["日", "月", "火", "水", "木", "金", "土"] %>
<%# calc_periods_ary = [@calc_periods_val, @calc_periods_prof] %>
<% tb_cnt = 0 %>
<div data-scope-path="shared/header">
  <h1 class="sub-title"><%= @base %>利益表（評価売）</h1>
  <%= render "shared/header" %>
</div>
<div style="display:flex;"><%# サイドバーとメインバーを分ける %>
  <div data-scope-path="shared/side_bar"><%# サイドバー %>
    <%= render "shared/sidebar" %>
  </div><%# サイドバー %>
  <div data-scope-path="shares/date-progress"><%# メインバー %>
      <div data-scope-path="shares/index">
      <%= render "shared/result_links" %>
    </div>
    <hr>
    <p class="caution-txt"><%= alert %></p>
    <div class="date-head"><%# 日付切替 %>
      <h2>
        <%= link_to "<<",results_base_valuations_path(month: @month.ago(1.month),base: @base), class:"link","data-turbolinks": false %>
        <%= @month.month %>月進捗
        <%= link_to ">>",results_base_valuations_path(month: @month.since(1.month),base: @base), class:"link","data-turbolinks": false %>
      </h2>
    </div><%# 日付切替 %>
    <hr>
    <%# render_async valuation_path(month: @month, base: @base) %><%# 売上 %>
    <%= render_async standard_val_path(month: @month, base: @base) %><%# 基準値 %>
    <%= render_async productivity_path(month: @month, base: @base) %><%# 生産性 %>
    <%# render_async current_result_path(month: @month, base: @base) %><%# 成果 %>
  </div>
</div>