config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'results#index'
  resources :store_props do 
    collection { post :import }
    collection { get :export }
  end 

  resources :summit_clients, only: [:index, :show] do
    collection { post :import }
    collection { delete :all_delete }
  end

  resources :summits, expect: [:new, :create] do 
    collection { post :import }
    collection { post :import_price }
    collection { get :sw_error }
    collection { get :cancel }
    collection { delete :not_share_delete }
  end

  resources :summit_customer_props do 
    collection { post :import}
  end 

  resources :summit_error_histories do 
    collection { post :import }
  end 

  resources :summit_billing_amounts do 
    collection { post :import }
  end 

  resources :summit_date_progresses, only: [:index] do 
    collection {get :base}
  end 

  resources :summit_date_progresses, only: :show,param: :user_id


  resources :pranesses, expect: [:new, :create] do 
    collection { 
      post :import 
      get :simplified_chart
      get :not_payment
    }
  end 

  resources :payment_pranesses do 
    collection { 
      post :import 
      get :year_profit
      get :year_valuation
      get :not_payment
    }
  end 

  get "year_profit_price", to: "payment_pranesses#year_profit_price", as: "year_profit_price"
  get "year_profit_len", to: "payment_pranesses#year_profit_len", as: "year_profit_len"
  get "year_val_price", to: "payment_pranesses#year_val_price", as: "year_val_price"
  get "year_val_len", to: "payment_pranesses#year_val_len", as: "year_val_len"

  resources :praness_options do 
    collection {
      post :import 
    }
  end 

  resources :dmers do 
    collection { post :import }
    collection { get :index_export }
    collection { get :export }
    collection { get :simple_conf }
    collection { get :simple_conf_year }
    collection { get :deficiency }
  end 
  
  resources :stocks do 
    collection { post :import }
    resources :stock_histories
    resources :return_histories
  end 

  resources :aupays, expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :paypays, expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :airpays do
    collection { 
      post :import 
      get :simple_conf 
    }
  end
  
  resources :stock_histories, only: [:destroy]
  resources :return_histories, only: [:destroy]
  
  resources :pandas, expect: [:new, :create] do 
    collection {post :import}
  end 

  resources :users do 
    collection {post :comment_new}
    collection {put :comment_update}
  end

  resources :shifts,expect: [:show] do 
    collection do
      post :update_month
      delete :delete_month
      get :cashless
    end
  end 

  resources :shifts, only: :show,param: :user_id

  resources :panda_profits, only: :index

  resources :results,expect: [:show]  do 
    get 'result_cashes/new'
    post 'result_cashes/create'
    get 'result_types/new'
    post 'result_types/create'
    get 'result_casas/new'
    get 'result_summits/new'
    post 'result_summits/create'
    get 'type_reference_values/new'
    post 'type_reference_values/create'
    collection { 
      post :import 
      get :export
      get :date_progress
      get :monthly_progress
      get :ranking
      get :gross_profit
      get :profit
      get :base_profit
      get :daily_report
      get :dup_index
      post :comment_new
      put :comment_update
      get :out_come
      get :base_productivity
      get :team_productivity
      get :person_productivity
      get :product_status
      get :slmt_list
      get :deficiency
      get :inc_or_dec
      get :valuation_list
    }
  end
  resources :type_reference_values, only: [:edit, :update]

  resources :result_types do 
    resources :deal_attributes do
      collection do
        get :edit_all
        patch :update_all
      end
    end
end

  resources :results, only: :show, param: :result_id
  get "date_fin/:id", to: "results#date_fin", as: "date_fin"
  get "weekly_fin/:id", to: "results#weekly_fin", as: "weekly_fin"
  get "out_val/:id", to: "results#out_val", as: "out_val"
  get "out_val_all/:id", to: "results#out_val_all", as: "out_val_all"
  get "out_val_type/:id", to: "results#out_val_type", as: "out_val_type"
  get "store_val/:id", to: "results#store_val", as: "store_val"
  get "store_val_all/:id", to: "results#store_val_all", as: "store_val_all"
  get "visit_type_val/:id", to: "results#visit_type_val", as: "visit_type_val"

  get "monthly_get", to: "results#monthly_get", as: "monthly_get"
  get "monthly_get_base", to: "results#monthly_get_base", as: "monthly_get_base"
  get "sales_and_def", to: "results#sales_and_def", as: "sales_and_def"
  get "user_list", to: "results#user_list", as: "user_list"
  
  
  resources :results_base_valuations, only: :index
  get "valuation", to: "results_base_valuations#valuation", as: "valuation"
  get "standard_val", to: "results_base_valuations#standard_val", as: "standard_val"
  get "productivity", to: "results_base_valuations#productivity", as: "productivity"
  get "current_result", to: "results_base_valuations#current_result", as: "current_result"


  resources :ojts, only: :index do 
    collection { get :export }
    collection { get :index_export }
    collection { get :summary_export }
  end 
  resources :ojts, only: :show, param: :result_id

  resources :result_cashes do 
    collection { post :import}
  end
  resources :result_casas, expect: [:new, :create]
  resources :result_summits, expect: :show do 
    collection { get :base_profit }
    collection { get :person_data }
    collection { get :repeal_data }
    collection { get :sw_error_data }
    collection { get :error_history_data }
    collection { get :customer_prop_data }
    collection { get :billing_data }
    collection { get :prediction_data }
  end 
  resources :result_summits, only: :show,param: :user_id
  
  resources :n_results do 
    collection { post :import }
  end  

  resources :products
  
  resources :display_periods
  
  resources :trouble_ns do 
    collection { post :import }
  end

  resources :rakuten_casas ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :trouble_sses ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :st_insurances ,expect: [:new, :create] do 
    collection { post :import }
  end 

  resources :rakuten_pays do 
    collection { 
      post :import
      get :index_export 
      get :deficiency
      get :deficiency_new
      get :simple_conf
      get :simple_conf_year
    }
  end 

  resources :error_pages
  
  resources :costs 

  resources :product_checkers, only: [:index]
  resources :product_tests, only: [:index]
  
  resources :result_sales, only: [:index] do 
    collection { post :import }
  end 

  resources :comments

  resources :def_respondings, only: [:index]
  
  resources :settlements, only: [:index]
  resources :other_products
  resources :dmer_stocks
  resources :product_targets
  resources :demaekans, only: [:index] do 
    collection {post :import}
  end 

  resources :profits, only: [:index] do 
    collection {get :sum_export}
    collection {get :index_export}
    collection {get :profit_export_by_spreadsheet}
    collection {get :product_export_by_spreadsheet}
  end
  # get 'profits', to: 'profits#index' do 
  #   collection {get :sum_export}
  # end 

  resources :calc_periods do 
    collection {
      get :cash_csv_export
      get :cash_valuation_csv_export
      get :weekly_data
    }
  end 

  get "val_users", to: "calc_periods#val_users", as: "val_users"

  
  resources :dmer_date_progresses do 
    collection {get :progress_create}
    collection {get :csv_export}
    collection {get :date_destroy}
  end 
  
  resources :aupay_date_progresses do 
    collection {get :progress_create}
    collection {get :csv_export}
    collection {get :date_destroy}
  end 

  resources :paypay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :rakuten_pay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end

  resources :airpay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :demaekan_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :austicker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :dmersticker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :airpaysticker_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :cash_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :itsses do 
    collection {post :import}
  end 

  resources :itss_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 

  resources :usen_pay_date_progresses do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  
  resources :other_product_date_progresses, only: [:index] do 
    collection {get :progress_create}
    collection {get :date_destroy}
  end 
  resources :airpay_stickers do 
    collection {post :import}
    collection {get :date_destroy}
  end 


  resources :payment_cashes 
  resources :payment_dmers do 
    collection { 
      post :import
      get :not_payment
      get :conf_index
      get :result1
      get :result2
      get :result3
    }
  end 

  resources :payment_dmer_senbais do 
    collection { 
      post :import
      get :not_payment
      get :conf_index
      get :result
    }
  end 

  resources :payment_rakuten_pays do 
    collection { 
      post :import
      get :not_payment
      get :conf_index

app/models/calc_period.rb
class CalcPeriod < ApplicationRecord

  with_options presence: true do 
    # 商材名
    validates :name
    validates :sales_category
    # 獲得期間
    validates :start_date_month  ,numericality: {only_integer: true, greater_than_or_equal_to: -1, less_than_or_equal_to: 2}
    validates :start_date_day    ,numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 30}
    validates :end_date_month    ,numericality: {only_integer: true, greater_than_or_equal_to: -1, less_than_or_equal_to: 2}
    validates :end_date_day      ,numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 30}
    # 締め日
    validates :closing_date_month,numericality: {only_integer: true, greater_than_or_equal_to: -1, less_than_or_equal_to: 2}
    validates :closing_date_day  ,numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 30}
  end  

  def this_moth_per_float
    this_month_per.to_f / 100
  end 
  def prev_moth_per_float
    prev_month_per.to_f / 100
  end 

  def set_month_per_float
    {:this_month_per => this_moth_per_float,:prev_month_per => prev_moth_per_float }
  end 
end

app/helpers/calc_periods_helper.rb
module CalcPeriodsHelper
end

app/views/calc_periods/_val_users.html.erb
<h2>◆評価売成果一覧</h2><br>
  <div style="display: flex;">
  <% bases = ["中部SS","関西SS","関東SS", "九州SS","2次店"] %>
    <% bases.each do |base| %>
      <div>
        <h2><%= base %></h2>
        <% @users.where(base: base).each do |user| %>
          <p class="link-text"><%= link_to user.name, out_come_results_path(u_id: user.id),class: "reset-link" %></p>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/calc_periods/index.html.erb
<% days = ["日", "月", "火", "水", "木", "金", "土"] %>
<% calc_periods_ary = [@calc_periods_val, @calc_periods_prof] %>
<% tb_cnt = 0 %>
<div data-scope-path="shared/header">
  <h1 class="sub-title">売上計算期間設定</h1>
  <%= render "shared/header" %>
</div>
<div style="display:flex;">
<div data-scope-path="shared/side_bar">
  <%= render "shared/sidebar" %>
</div>
<div data-scope-path="shares/index">
  <div class="main">
    <p class="s-text"><%= alert %></p>
    <h2>
      <%= link_to "<<",calc_periods_path(month: @month.ago(1.month)), class:"link" %>
      <%= @month.month %>月利益表設定内容
      <%= link_to ">>",calc_periods_path(month: @month.since(1.month)), class:"link" %>
      <button class="new-btn"><%= link_to "新規登録", new_calc_period_path,class: "reg-link" %></button>
    </h2>
    <hr>
      <h2>◆進捗資料の作成（<%= link_to "固定費一覧",fixed_sales_path, class:"link" %>）</h2>
    <% if @activity_bases.present? %><%# 活動拠点が登録されていないと実売資料が作れないようにする。 %>
      <table>
        <tr>
          <th>進捗データ作成</th>
          <th>進捗</th>
          <th>最終作成日</th>
          <th>CSV出力</th>
        </tr>
        <tr>
          <td><%= link_to "dメル", progress_create_dmer_date_progresses_path(month: @month),data: {confirm: "#{@month.month}月の売上結果を保存してもよろしいですか？"}, class: "link" %></td>
          <td><%= link_to "詳細", dmer_date_progresses_path(month: @month),"data-turbolinks": false, class: "link" %></td>
          <td><%= @dmer_date_progresses_last_update %></td>
          <td></td>
        </tr>
        <tr> 
          <% if @dmer_senbai_users.present? %>
          <td><%= link_to "dメル専売", progress_create_dmer_senbai_date_progresses_path(month: @month),data: {confirm: "#{@month.month}月の売上結果を保存してもよろしいですか？"}, class: "link" %></td>
          <td><%= link_to "詳細", dmer_senbai_date_progresses_path(month: @month),"data-turbolinks": false, class: "link" %></td>
          <% else %>
          <td><%= link_to "dメル専売の人員登録", dmer_senbai_users_path(month: @month),data: {}, class: "red" %></td>
          <td><%= link_to "詳細", dmer_senbai_date_progresses_path(month: @month),"data-turbolinks": false, class: "link" %></td>
          <% end %>
          <td><%= @dmer_senbai_date_progresses_last_update %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= link_to "auPay", progress_create_aupay_date_progresses_path(month: @month),data: {confirm: "#{@month.month}月の売上結果を保存してもよろしいですか？"}, class: "link" %></td>
          <td><%= link_to "詳細", aupay_date_progresses_path(month: @month),"data-turbolinks": false, class: "link" %></td>
          <td><%= @aupay_date_progresses_last_update %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= link_to "PayPay", progress_create_paypay_date_progresses_path(month: @month),data: {confirm: "#{@month.month}月の売上結果を保存してもよろしいですか？"}, class: "link" %></td>
          <td><%= link_to "詳細", paypay_date_progresses_path(month: @month),"data-turbolinks": false, class: "link" %></td>
          <td><%= @paypay_date_progresses_last_update %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= link_to "楽天Pay", progress_create_rakuten_pay_date_progresses_path(month: @month),data: {confirm: "#{@month.month}月の売上結果を保存してもよろしいですか？"}, class: "link" %></td>
          <td><%= link_to "詳細", rakuten_pay_date_progresses_path(month: @month),"data-turbolinks": false, class: "link" %></td>
          <td><%= @rakuten_pay_date_progresses_last_update %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= link_to "AirPay", progress_create_airpay_date_progresses_path(month: @month),data: {confirm: "#{@month.month}月の売上結果を保存してもよろしいですか？"}, class: "link" %></td>
          <td><%= link_to "詳細", airpay_date_progresses_path(month: @month),"data-turbolinks": false, class: "link" %></td>
          <td><%= @airpay_date_progresses_last_update %></td>
          <td></td>
        </tr>
        <% @other_products.group(:product_name).each do |product| %>
        <tr>
          <td><%= link_to "#{product.product_name}", progress_create_other_product_date_progresses_path(month: @month, product_name: product.product_name),data: {confirm: "#{@month.month}月#{product.product_name}：売上結果を保存してもよろしいですか？"}, class: "link" %></td>
          <td><%= link_to "詳細", other_product_date_progresses_path(month: @month, product_name: product.product_name),"data-turbolinks": false, class: "link" %></td>
          <td><%= OtherProductDateProgress.where(product_name: product.product_name).where(date: @month.all_month).maximum(:create_date)  %></td>
          <td></td>
        </tr>
        <% end %>
        <tr>
          <td><%= link_to "UsenPay", progress_create_usen_pay_date_progresses_path(month: @month),data: {confirm: "#{@month.month}月の売上結果を保存してもよろしいですか？"}, class: "link" %></td>
          <td><%= link_to "詳細", usen_pay_date_progresses_path(month: @month),"data-turbolinks": false, class: "link" %></td>
          <td><%= @usen_pay_date_progresses_last_update %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= link_to "キャッシュ合計", progress_create_cash_date_progresses_path(month: @month),data: {confirm: "#{@month.month}月の売上結果を保存してもよろしいですか？"}, class: "link" %></td>
          <td><%= link_to "詳細", cash_date_progresses_path(month: @month),"data-turbolinks": false, class: "link" %></td>
          <td><%= @cash_date_progresses_last_update %></td>
          <td><%= link_to "Excelで出力(実売資料)",calc_periods_path(format: :xlsx,month: @month), data: {confirm: "Excelを出力しますか？"}, class: "link",id:'download-csv' %></td>
        </tr>
      </table>
    <% else %>
      <h2 class="caution-text"><%= @month.month %>月の活動拠点が登録されておりません。登録してから実売資料を作成してください。</h2><br>
      <p class="caution-text"><%= link_to "※活動拠点を登録するページへ移動",activity_bases_path(month: @month), class: "red" %></p>
    <% end %>
    <% calc_periods_ary.each do |calc_periods| %>
    <% if tb_cnt == 0 %>
      <h2>◆評価売</h2>
      <%# 重複確認 %>
    <% else %>
    <h2>◆実売</h2>
    <% end %>
    <% calc_duplicate = calc_periods.group(:name).having("count(*) >= 2") %>
    <% if calc_duplicate.present? %>
    <p class="nav-text" style="color: red;">案件重複
      <% calc_duplicate.each do |db| %>
        <%= db.name %>, 
      <% end %>
      削除するか"案件名"、もしくは"売上区分"を変更してください。
    </p>
    <% end %>
    <% tb_cnt += 1 %>
    <table>
      <thead>
        <tr>
          <th>商材</th>
          <th>売上区分</th>
          <th>集計期間（始）</th>
          <th>集計期間（終）</th>
          <th>締め日</th>
          <th>当月成果率（％）</th>
          <th>過去月成果率（％）</th>
          <th>単価</th>
          <th>インセン１（件数）</th>
          <th>インセン１（単価）</th>
          <th>インセン２（件数）</th>
          <th>インセン２（単価）</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% calc_periods.each do |calc_period| %>
          <%# 獲得期間の日付 %>
          <% if calc_period.start_date_day == 0 %>
            <% start_date_day = @month.end_of_month.day %>
          <% else %>
            <% start_date_day = "#{calc_period.start_date_day}日" %>
          <% end %>
          <% if calc_period.end_date_day == 0 %>
            <% end_date_day = @month.end_of_month.day %>
          <% else %>
            <% end_date_day = "#{calc_period.end_date_day}日" %>
          <% end %>
          <%# 締め日の日付 %>
          <% if calc_period.closing_date_day == 0 %>
            <% closing_date_day = @month.end_of_month.day %>
          <% else %>
            <% closing_date_day = "#{calc_period.closing_date_day}日" %>
          <% end %>
        <tr>
          <td><%= calc_period.name %></td>
          <td><%= calc_period.sales_category %></td>
          <%# 獲得期間 %>
            <td><%= @month.since(calc_period.start_date_month.month).month %>月<%= start_date_day %></td>
            <td><%= @month.since(calc_period.end_date_month.month).month %>月<%= end_date_day %></td>
          <%# 締め日 %>
            <td><%= @month.since(calc_period.closing_date_month.month).month %>月<%= closing_date_day %></td>
            <td><%= (calc_period.this_month_per * 100).to_i %>%</td>
            <td><%= (calc_period.prev_month_per * 100).to_i %>%</td>
            <td><%= calc_period.price.to_s(:delimited) rescue "" %></td>
            <td><%= calc_period.bonus1_len rescue "" %></td>
            <td><%= calc_period.bonus1_price.to_s(:delimited) rescue "" %></td>
            <td><%= calc_period.bonus2_len rescue "" %></td>
            <td><%= calc_period.bonus2_price.to_s(:delimited) rescue "" %></td>
            <td><%= link_to "編集", edit_calc_period_path(calc_period),class: "link" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
    <p class="caution-text">※過去月も<%= Date.today.month %>月と同じ基準で利益表の計算を行っております。</p>

    <h2>◆目標売上</h2>
    <table>
      <thead>
        <tr>
          <th>売上</th>
          <th>オーナー不在:a</th>
          <th>対面:b(率)</th>
          <th>フル:c(率)</th>
          <th>情報聞いた:d1(率)</th>
          <th>認証キー回収:d2(率)</th>
          <th>成約:e(率)</th>
          <th>成約:e(成約/フル)</th>
        </tr>
      </thead>
      <tbody>
        <% @baseline_sales.each do |baseline_sale| %>
        <tr>
          <td><%= link_to baseline_sale.sales_goal, edit_baseline_sale_path(baseline_sale.id),"data-turbolinks": false, class: "link" %></td>
          <% if baseline_sale.baseline_metrics.present? %>
            <% baseline_a = baseline_sale.baseline_metrics.find_by(metric_name: "a") %>
            <td><%=
              link_to baseline_a.metric_val, edit_baseline_sale_baseline_metric_path(baseline_sale, baseline_sale.baseline_metrics.find_by(metric_name: "a")), "data-turbolinks": false, class: "link" rescue link_to "入力", new_baseline_sale_baseline_metric_path(baseline_sale.id, metric_name: "a"),"data-turbolinks": false, class: "link" 
            %></td>
            <% metric_name_list = ["b", "c", "d1", "d2", "e", "e_rate_from_full_talk"] %>
            <% metric_name_list.each do |metric_name| %>
              <% target_baseline_metric = baseline_sale.baseline_metrics.find_by(metric_name: metric_name) %>
              <% target_metric_per = baseline_sale.baseline_metrics.find_by(metric_name: metric_name).metric_per rescue "未設定" %>
              <td><%= link_to "#{target_baseline_metric.metric_val} (#{target_metric_per})%", edit_baseline_sale_baseline_metric_path(baseline_sale, target_baseline_metric),"data-turbolinks": false, class: "link" rescue link_to "入力", new_baseline_sale_baseline_metric_path(baseline_sale.id, metric_name: metric_name),"data-turbolinks": false, class: "link" %></td>
            <% end %>

          <% else %>
            <td><%= link_to "入力", new_baseline_sale_baseline_metric_path(baseline_sale.id, metric_name: "a"),"data-turbolinks": false, class: "link" %></td>
            <td><%= link_to "入力", new_baseline_sale_baseline_metric_path(baseline_sale.id, metric_name: "b"),"data-turbolinks": false, class: "link" %></td>
            <td><%= link_to "入力", new_baseline_sale_baseline_metric_path(baseline_sale.id, metric_name: "c"),"data-turbolinks": false, class: "link" %></td>
            <td><%= link_to "入力", new_baseline_sale_baseline_metric_path(baseline_sale.id, metric_name: "d1"),"data-turbolinks": false, class: "link" %></td>
            <td><%= link_to "入力", new_baseline_sale_baseline_metric_path(baseline_sale.id, metric_name: "d2"),"data-turbolinks": false, class: "link" %></td>
            <td><%= link_to "入力", new_baseline_sale_baseline_metric_path(baseline_sale.id, metric_name: "e"),"data-turbolinks": false, class: "link" %></td>
            <td><%= link_to "入力", new_baseline_sale_baseline_metric_path(baseline_sale.id, metric_name: "e_rate_from_full_talk"),"data-turbolinks": false, class: "link" %></td>
          <% end %>
        </tr>

        <% end %>
        <tr>
          <td><%= link_to "目標売上入力", new_baseline_sale_path,"data-turbolinks": false, class: "link" %></td>
        </tr>
      </tbody>
    </table>

    <hr>
    <%= render_async val_users_path %>
  </div>
</div>

app/views/calc_periods/weekly_data.html.erb
<% days = ["日", "月", "火", "水", "木", "金", "土"] %>
<% calc_periods_ary = [@calc_periods_val, @calc_periods_prof] %>
<% tb_cnt = 0 %>
<div data-scope-path="shared/header">
  <h1 class="sub-title">売上計算期間設定</h1>
  <%= render "shared/header" %>
</div>
<div style="display:flex;">
<div data-scope-path="shared/side_bar">
  <%= render "shared/sidebar" %>
</div>
<div data-scope-path="shares/date-progress">
    <p class="s-text"><%= alert %></p>
    <h2>
      <%= link_to "<<",weekly_data_calc_periods_path(month: @month.ago(1.month)), class:"link" %>
      <%= @month.month %>月週間生産性（<%= link_to "戻る",calc_periods_path(month: @month), class:"link" %>）
      <%= link_to ">>",weekly_data_calc_periods_path(month: @month.since(1.month)), class:"link" %>
    </h2>
      <table class="progress-tb">
        <thead>
          <tr>
            <th class="progress-th1" colspan="4">基本情報</th>
            <th class="progress-th1" colspan="3">シフト</th>
            <% week_start = 1 %>
            <% week_end = 7 %>
            <% 5.times do |i| %>
            <% if week_end >= @month.end_of_month.day %>
              <% week_end = @month.end_of_month.day %>
            <% end %>
            <th class="progress-th1" colspan="3"><%= i + 1 %>週目（<%= week_start %>〜<%= week_end %>）</th>
            <% week_start += 7 %>
            <% week_end += 7 %>
            <% end %>
          </tr>
          <tr>
            <th class="progress-th2">拠点</th>
            <th class="progress-th2">氏名</th>
            <th class="progress-th2">役職</th>
            <th class="progress-th2">予定シフト</th>
            <th class="progress-th2">消化シフト</th>
            <th class="progress-th2">残シフト</th>
            <% 5.times do %>
            <th class="progress-th2">dメル</th>
            <th class="progress-th2">AirPay</th>
            <th class="progress-th2">UsenPay</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @bases.each do |base| %><%# 拠点ごとのループ %>
          <% @users.where(base: base).order("users.position_sub ASC").order("users.id ASC").each do |user| %><%# ユーザーごとのループ %>
          <tr>
            <td class="progress-td"><%= base %></td>
            <td class="progress-td"><%= user.name %></td>
            <td class="progress-td"><%= user.position_sub %></td>
            <td class="progress-td"><%= @shifts.where(user_id: user.id).length %></td>
            <td class="progress-td"><%= @results.where(user_id: user.id).length %></td>
            <td class="progress-td"><%= @shifts.where(user_id: user.id).length - @results.where(user_id: user.id).length %></td>
            <% week_start = 1 %>
            <% week_end = 7 %>
            <% 5.times do %><%# 週ごとの商材の獲得数を出力 %>
            <% if week_end >= @month.end_of_month.day %>
              <% week_end = @month.end_of_month.day %>
            <% end %>
            <td class="progress-td"><%= (@dmers.where(user_id: user.id).where(date: Date.new(@month.year, @month.month,week_start)..Date.new(@month.year, @month.month,week_end)).length.to_f / @results.where(user_id: user.id).where(date: Date.new(@month.year, @month.month,week_start)..Date.new(@month.year, @month.month,week_end)).length).round(1) rescue 0 %></td>
            <td class="progress-td"><%= (@airpays.where(user_id: user.id).where(date: Date.new(@month.year, @month.month,week_start)..Date.new(@month.year, @month.month,week_end)).length.to_f / @results.where(user_id: user.id).where(date: Date.new(@month.year, @month.month,week_start)..Date.new(@month.year, @month.month,week_end)).length).round(1) rescue 0 %></td>
            <td class="progress-td"><%= (@usen_pays.where(user_id: user.id).where(date: Date.new(@month.year, @month.month,week_start)..Date.new(@month.year, @month.month,week_end)).length.to_f / @results.where(user_id: user.id).where(date: Date.new(@month.year, @month.month,week_start)..Date.new(@month.year, @month.month,week_end)).length).round(1) rescue 0 %></td>
            <% week_start += 7 %>
            <% week_end += 7 %>
            <% end %><%# /週ごとの商材の獲得数を出力 %>
          </tr>
          <% end %><%# /ユーザーごとのループ %>
          <% end %><%# /拠点ごとのループ %>
        </tbody>
      </table>
  </div>
</div>